version: 2.1
orbs:
  node: circleci/node@5.0.1

jobs:
  env:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.17'
      - run: node --version
      - run: yarn
workflows:
  coding-publisher: 
    jobs:
      - env
      - node/run:
          yarn-run: publish
      
      
